### ISSUE TITLE
TRRT functionality for only doing the first TermRef in a document

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-tools#7]
There are documents in which all occurrances of a term are authored as a TermRef, where in the rendered website, this makes for a sloppy view. @Michiel-s had an idea in the order of only having the first occurrance of a particular term have an actual reference, leaving any following TermRef for that term untouched.

This issue calls for discussing the specs to support that.

I think we might have a `-c2` or `--converter2` option, that specifies how any second and following termrefs should be converted; by absence of that option, the regular converter would be used.

**Comment by Ca5e** [comment]
Proposing the following.
Instead of using `-c2` or `--converter2`, we are able to provide the TRRT with `-c[n]` or `--converter[n]`, where `n` will refer to the count of the term ref occurrence from which we would like to use the corresponding converter. It should be decided on how count of occurrence is kept, but I believe counting the occurrence of a certain `termid` per processed file may be the correct choice.
When using `converter[n]` with an `n` lower than 1, it will behave the same as using `converter` without a provided `n`.

**Comment by RieksJ** [comment]
'termid' seems logical, but - from another perspective - so would 'showtext'. @Michiel-s , any suggestions?

**Comment by Ca5e** [comment]
The newest versions of the TRRT is now configurable with the `converter[n]` option. For now, the `termid` field is used to count the occurrences of a certain term.

**Comment by RieksJ** [comment]
Ok. Let's close this issue when 

- [ ] we've played a bit with it, and 
- [x] the documentation is updated. @Ca5e : can you add the stuff that is necessary to the [TRRT documentation](https://github.com/tno-terminology-design/tev2-specifications/blob/main/docs/spec-tools/12-trrt.md)

**Comment by Ca5e** [comment]
I've also added the converter[error] option to the TRRT, documentation on this still has to be done.

**Comment by RieksJ** [comment]
Decisions:
- converter array starts with index 1 (i.e. first TermRef occurrance is done by converter[1], etc.)
- there is no default converter, TRRT will require the user to specify it.
